storeData = {
  products: [
    {
      name: "Trade Up Model List 1(On Top 3,000.-)",
      variants: [
      ],
      promo: [
        "iPhone ",
        "iPhone 12 ProMax",
        "iPhone 13 ",
        "iPhone 13 Pro",
        "iPhone 13 ProMax",
        "iPhone 14",
        "iPhone 14 Plus",
        "Phone 15",
        "IQOO",
        "IQOO 13",
        "Realme",
        "Realme GT7 Pro",
        "Realme GT7",
        "Realme GT6",
        "OnePlus",
        "OnePlus 12",
        "Honor",
        "Honor 200Pro",
        "Honor Magic V2",
        "Honor Magic 7 Pro",
        "Honor Magic 7",
        "Honor Magic 6Pro",
        "Honor Magic 6",
        "oppo",
        "oppo Find X8",
        "oppo Find X7 Ultra",
        "oppo Find X7",
        "oppo Find N3",
        "oppo Reno14 Pro",
        "oppo Reno14",
        "Samsung",
        "Samsung S25 Plus",
        "Samsung S25",
        "Samsung S23 Ultra",
        "Samsung S22 Ultra",
        "Samsung Z Flip 6",
        "Samsung Z Flip 5",
        "Huawei",
        "Huawei Pura 70 Ultra",
        "Huawei Pura 70 ProPlus",
        "Huawei Pura 70 Pro",
        "Huawei Pura 70",
        "Huawei Mate 60 Pro",
        "Huawei Mate 60",
        "Vivo",
        "Vivo X200FE",
        "Vivo X200",
        "Vivo X100 Pro",
        "Vivo X100",
        "Vivo X90 Pro Plus",
        "Xiaomi",
        "Xiaomi 15 Pro",
        "Xiaomi 15",
        "Xiaomi 14Pro",
        "Xiaomi 14",
        "Xiaomi 13 Ultra",
        "Xiaomi 13 Pro"
      ]
    },

    {
      name: "Trade Up Model List 2(On Top 4,000.-)",
      variants: [
      ],
      promo: [
        "iPhone ",
        "iPhone 16 ProMax",
        "iPhone 16 Pro",
        "iPhone 16 Plus",
        "iPhone 16 ",
        "iPhone 16 e",
        "iPhone 15 ProMax",
        "iPhone 15 Pro",
        "iPhone 15 Plus",
        "oppo",
        "oppo Find N5",
        "oppo Find X8 Ultra",
        "oppo Find X8 Pro",
        "Samsung",
        "Samsung S25 Ultra",
        "Samsung S24 Ultra",
        "Samsung Z Flip 6",
        "Huawei",
        "Huawei Mate X6",
        "Huawei Mate X5",
        "Huawei Mate 60 RS",
        "Vivo",
        "Vivo X200Pro"
      ]
    },
   ]
};